### ISSUE TITLE
(MR/VR) Increase global scale range x2

### ISSUE THREAD

**Issue by Aktion** [fortellgames/bw_bugtracker#221]

**Comment by dianateper** [comment]
Fixed in the latest update 2.0.0.105 (96)

**Comment by DaviveCZ** [comment]
https://github.com/fortellgames/bw_bugtracker/issues/253
it's worth looking at this issue as it can become problem when trying to paint very tiny things.
since you can paint stuff like steering wheel and such. There was a time before the game's 33% got scalled down even more where i had issue painting over the steering wheel block when i needed that to be invisible.

**Comment by Aktion** [comment]
ok im closing this but keep #253 open
